# Generated by Django 5.2.5 on 2025-08-28 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
